try again to make if conditional work

diff --git a/.github/workflows/download-and-collate.yml b/.github/workflows/download-and-collate.yml
--- a/.github/workflows/download-and-collate.yml
+++ b/.github/workflows/download-and-collate.yml
@@ -88,34 +88,28 @@ jobs:
 
   validate-tei-xml:
     needs: create-tei-files
-    # if: needs.create-tei-files.outputs.filesChanged || inputs.forceCollate
+    if: ${{ (needs.create-tei-files.outputs.filesChanged == "true") || (inputs.forceCollate == "true") }}
     runs-on: [self-hosted, Linux]
     container:
       image: ghcr.io/dhuniwien/edition-tools
     continue-on-error: ${{ !inputs.blockOnValidation }}
-    outputs:
-      hackContinue: ${{ needs.create-tei-files.outputs.filesChanged || inputs.forceCollate }}
     steps: 
       - uses: actions/checkout@v3
       - name: Validate committed XML files
-        # if: ${{ needs.create-tei-files.outputs.filesChanged || inputs.forceCollate }}
         run: |
-          echo Run conditional evalutes to ${{ inputs.forceCollate || needs.create-tei-files.outputs.filesChanged }}
           verr=0
-          if [ ${{ inputs.forceCollate || needs.create-tei-files.outputs.filesChanged }} = true ]; then
-            # don't stop if a linter fails, instead make sure
-            # all files are checked by swallowing the return value
-            #
-            for FILE in transcription/tei-xml/*.xml
-            do
-              echo === $FILE ===
-              xmllint --noout --relaxng ${{ inputs.xml_schema }} "$FILE"
-              ret=$?
-              verr=$((verr + ret))
-            done
-            if [ $verr -ne 0 ]; then
-              echo "Some files failed to validate"
-            fi
+          # don't stop if a linter fails, instead make sure
+          # all files are checked by swallowing the return value
+          #
+          for FILE in transcription/tei-xml/*.xml
+          do
+            echo === $FILE ===
+            xmllint --noout --relaxng ${{ inputs.xml_schema }} "$FILE"
+            ret=$?
+            verr=$((verr + ret))
+          done
+          if [ $verr -ne 0 ]; then
+            echo "Some files failed to validate"
           fi
           exit $verr
             
@@ -129,20 +123,20 @@ jobs:
       - name: Tokenize all sections
         run: |
           # Workaround for broken conditional in validation step
-          if [ ${{ needs.validate-tei-xml.outputs.hackContinue }} = false ]; then
-            echo Hack conditional evaluates to ${{ needs.validate-tei-xml.outputs.hackContinue }}
-            echo Skipping tokenisation
-            exit 0
-          fi
+          # if [ ${{ needs.validate-tei-xml.outputs.hackContinue }} = false ]; then
+          #   echo Hack conditional evaluates to ${{ needs.validate-tei-xml.outputs.hackContinue }}
+          #   echo Skipping tokenisation
+          #   exit 0
+          # fi
           rm -rf tokenfiles && mkdir tokenfiles  # Make sure cruft is cleared out
           python3 /root/scripts/teixml2collatex.py transcription/tei-xml/ tokenfiles -c transcription/config --verbose
       - name: Collate section by section
         run: |
           # Workaround for broken conditional in validation step
-          if [ ${{ needs.validate-tei-xml.outputs.hackContinue }} = false ]; then
-            echo Skipping collation
-            exit 0
-          fi
+          # if [ ${{ needs.validate-tei-xml.outputs.hackContinue }} = false ]; then
+          #   echo Skipping collation
+          #   exit 0
+          # fi
           # Construct the base curl command depending on whether we have an API user/password
           CURLCMD='curl --silent'
           if [ -n ${{ secrets.API_HTUSER }} ]; then
